import { Michroma, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import SmoothScroll from "@/app/components/SmoothScroll";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${michroma.variable} min-h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans antialiased">
        <Header />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
